#!/bin/bash
#!/bin/zsh

# Base
alias yeet='rm -rf'
function updateall(){
    pacman -Syu
    yay -Syu
    kubectl krew update
    kubectl krew upgrade
}

# Terminal Tooling
alias vi="vim"
alias ls="ls --color=auto"
alias grep="grep --color=auto"

# Node
alias pn='pnpm'

# Git
alias branch='git branch --show-current'
alias reset='git reset --hard origin/$(branch)'
alias amend='git commit --amend --no-edit'
alias ammend='echo "Did you mean amend you stupid fucker? Yes you did." && amend'
alias force='git push --force-with-lease'
alias push='git push'
alias pull='git pull --rebase'

# Docker
alias docker='podman'

# General dev
alias release="shikai"
alias copilotfree="COPILOT_PROVIDER_TYPE=openai COPILOT_PROVIDER_BASE_URL=https://opencode.ai/zen/v1 COPILOT_PROVIDER_API_KEY='' COPILOT_MODEL=minimax-m2.5-free copilot"
alias copilotflash="COPILOT_PROVIDER_TYPE=openai COPILOT_PROVIDER_BASE_URL=https://opencode.ai/zen/v1 COPILOT_PROVIDER_API_KEY='sk-APxHRAqzVvl54JZiBhHLiKkeBkKFgpreBrNrGlwacaOtqgoD7qz1gU41mmInSawP' COPILOT_MODEL=deepseek-v4-flash-free copilot"

# Kubernetes
## General
alias k='kubectl'
alias kns='kubectl config set-context --current --namespace'
alias kctx='kubectl config use-context'

alias netshoot='kubectl run tmp-shell --rm -i --tty --image nicolaka/netshoot'
function netshootdebug(){
    kubectl debug "$1" -it --image=nicolaka/netshoot
}

# Terraform
alias tf='tofu'

# Dev setup
alias devsetup='~/.local/bin/devsetup'

# Minio
alias mc="mcli"

# Task
alias task='go-task'